# Generated by Django 5.2.8 on 2025-11-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_uploadedxml_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=255)),
                ('category_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'category',
                'ordering': ['category_name'],
                'indexes': [models.Index(fields=['category_name'], name='idx_category_name')],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('color_name', models.CharField(max_length=255)),
                ('color_type', models.CharField(max_length=255)),
                ('color_code', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'color',
                'ordering': ['color_name'],
                'indexes': [models.Index(fields=['color_name'], name='idx_color_name'), models.Index(fields=['color_type'], name='idx_color_type'), models.Index(fields=['color_type', 'color_name'], name='idx_color_type_name')],
            },
        ),
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('item_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'gears',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='idx_gear_name')],
            },
        ),
        migrations.CreateModel(
            name='Minifigure',
            fields=[
                ('item_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'minifigures',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='idx_minifigure_name')],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('item_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'parts',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='idx_part_name')],
            },
        ),
        migrations.CreateModel(
            name='PartWithColor',
            fields=[
                ('sn', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('item_id', models.CharField(max_length=255)),
                ('color_name', models.CharField(max_length=255)),
                ('item_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'parts_with_colors',
                'ordering': ['item_id'],
                'indexes': [models.Index(fields=['item_id'], name='idx_parts_with_color_id')],
            },
        ),
    ]
