# Generated by Django 5.2 on 2025-10-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbaord', '0003_uploadedxml'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedxml',
            name='file',
            field=models.FileField(upload_to='data/'),
        ),
    ]
